# Based on: https://github.com/clap-rs/clap/blob/master/.github/workflows/ci.yml

name: CI

permissions:
  contents: read

on:
  pull_request:
  push:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  ci:
    permissions:
      contents: none
    name: CI
    needs: [test, check, clippy]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  test:
    name: Test
    strategy:
      matrix:
        build: [linux, windows, mac]
        include:
          - build: linux
            os: ubuntu-latest
            rust: "stable"
          - build: windows
            os: windows-latest
            rust: "stable"
          - build: mac
            os: macos-latest
            rust: "stable"
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Setup Z3
        id: z3
        uses: cda-tum/setup-z3@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build: [msrv, debug, release]
        include:
          - build: msrv
            rust: 1.75.0 # MSRV
            target: x86_64-unknown-linux-gnu
            features: full
          - build: debug
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: debug
          - build: release
            rust: stable
            target: x86_64-unknown-linux-gnu
            features: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check
        env:
          TOOLCHAIN_TARGET: ${{ matrix.target }}
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75.0 # MSRV
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: cargo clippy
